fix : build apk v7 | Gerardo

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,120 +1,119 @@
-name: SoftionPro App CI/CD Workflow
+# name: SoftionPro App CI/CD Workflow
 
-on:
-  push:
-    branches:
-      - main
-      - feature/*
-      - hotfix/*
-  pull_request:
-    branches:
-      - main
-      - feature/*
-      - hotfix/*
+# on:
+#   push:
+#     branches:
+#       - main
+#       - feature/*
+#       - hotfix/*
+#   pull_request:
+#     branches:
+#       - main
+#       - feature/*
+#       - hotfix/*
 
-jobs:
-  setup:
-    runs-on: ubuntu-latest
-    permissions:
-      pull-requests: write
-      issues: write
-    steps:
-      - name: Checkout Código
-        uses: actions/checkout@v4.2.1
+# jobs:
+#   setup:
+#     runs-on: ubuntu-latest
+#     permissions:
+#       pull-requests: write
+#       issues: write
+#     steps:
+#       - name: Checkout Código
+#         uses: actions/checkout@v4.2.1
 
-      - name: Configurar Node.js
-        uses: actions/setup-node@v2
-        with:
-          node-version: '16'  # Actualizado a la versión 16
+#       - name: Configurar Node.js
+#         uses: actions/setup-node@v2
+#         with:
+#           node-version: '16'  # Actualizado a la versión 16
 
-      - name: Configurar Caché
-        uses: actions/cache@v2
-        with:
-          path: ~/.npm
-          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
+#       - name: Configurar Caché
+#         uses: actions/cache@v2
+#         with:
+#           path: ~/.npm
+#           key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
 
-      - name: Instalar Dependencias
-        run: npm install
+#       - name: Instalar Dependencias
+#         run: npm install
 
-      - name: Comentar en PR
-        if: github.event_name == 'pull_request'
-        uses: actions/github-script@v4
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            github.issues.createComment({
-              issue_number: context.payload.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: 'Se han realizado cambios en este PR. Por favor, revisen.'
-            })
+#       - name: Comentar en PR
+#         if: github.event_name == 'pull_request'
+#         uses: actions/github-script@v4
+#         with:
+#           github-token: ${{ secrets.GITHUB_TOKEN }}
+#           script: |
+#             github.issues.createComment({
+#               issue_number: context.payload.number,
+#               owner: context.repo.owner,
+#               repo: context.repo.repo,
+#               body: 'Se han realizado cambios en este PR. Por favor, revisen.'
+#             })
 
-  run-tests: 
-    runs-on: ubuntu-latest 
-    needs: [setup] 
-    steps: 
-      - name: Checkout Código 
-        uses: actions/checkout@v2 
+#   run-tests: 
+#     runs-on: ubuntu-latest 
+#     needs: [setup] 
+#     steps: 
+#       - name: Checkout Código 
+#         uses: actions/checkout@v2 
 
-      - name: Configurar Node.js 
-        uses: actions/setup-node@v2 
-        with: 
-          node-version: '16' 
+#       - name: Configurar Node.js 
+#         uses: actions/setup-node@v2 
+#         with: 
+#           node-version: '16' 
 
-      - name: Instalar Dependencias 
-        run: npm install 
+#       - name: Instalar Dependencias 
+#         run: npm install 
 
-      - name: Instalar jest-expo globalmente
-        run: npm install -g jest-expo
+#       - name: Instalar jest-expo globalmente
+#         run: npm install -g jest-expo
 
-      # Ejecutar las pruebas
-      - name: Ejecutar Pruebas
-        run: npm test
+#       # Ejecutar las pruebas
+#       - name: Ejecutar Pruebas
+#         run: npm test
 
-      # Forzar finalización de procesos de Jest
-      - name: Finalizar Proceso de Jest
-        run: |
-          echo "Finalizando proceso de Jest"
-          kill $(ps aux | grep '[j]est' | awk '{print $2}') || true
+#       # Forzar finalización de procesos de Jest
+#       - name: Finalizar Proceso de Jest
+#         run: |
+#           echo "Finalizando proceso de Jest"
+#           kill $(ps aux | grep '[j]est' | awk '{print $2}') || true
 
 
-  notify-on-success:
-    runs-on: ubuntu-latest
-    needs: [build]
-    if: success()  # Solo se ejecuta si run-tests tuvo éxito
-    steps:
-      - name: Notificar Éxito
-        uses: dawidd6/action-send-mail@v3
-        with:
-          server_address: smtp.gmail.com
-          server_port: 465
-          username: ${{ secrets.GMAIL_ADDRESS }}
-          password: ${{ secrets.GMAIL_APP_PASSWORD }}
-          subject: El repositorio ha pasado las pruebas correctamente.
-          body: El repositorio ha superado las pruebas correctamente. Puedes ver los detalles en https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}+event%3A${{ github.event_name }}
-          to: ${{ secrets.GMAIL_ADDRESS_RECIPIENT }}
-          from: ${{ secrets.GMAIL_ADDRESS }}
+#   notify-on-success:
+#     runs-on: ubuntu-latest
+#     needs: [build]
+#     if: success()  # Solo se ejecuta si run-tests tuvo éxito
+#     steps:
+#       - name: Notificar Éxito
+#         uses: dawidd6/action-send-mail@v3
+#         with:
+#           server_address: smtp.gmail.com
+#           server_port: 465
+#           username: ${{ secrets.GMAIL_ADDRESS }}
+#           password: ${{ secrets.GMAIL_APP_PASSWORD }}
+#           subject: El repositorio ha pasado las pruebas correctamente.
+#           body: El repositorio ha superado las pruebas correctamente. Puedes ver los detalles en https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}+event%3A${{ github.event_name }}
+#           to: ${{ secrets.GMAIL_ADDRESS_RECIPIENT }}
+#           from: ${{ secrets.GMAIL_ADDRESS }}
 
-  notify-on-failure:
-    runs-on: ubuntu-latest
-    needs: [build]
-    if: failure()  # Solo se ejecuta si run-tests falla
-    steps:
-      - name: Notificar Error
-        uses: dawidd6/action-send-mail@v3
-        with:
-          server_address: smtp.gmail.com
-          server_port: 465
-          username: ${{ secrets.GMAIL_ADDRESS }}
-          password: ${{ secrets.GMAIL_APP_PASSWORD }}
-          subject: El repositorio ha fallado en las pruebas.
-          body: El repositorio ha fallado en las pruebas. Puedes ver los detalles en https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}+event%3A${{ github.event_name }}
-          to: ${{ secrets.GMAIL_ADDRESS_RECIPIENT }}
-          from: ${{ secrets.GMAIL_ADDRESS }}
+#   notify-on-failure:
+#     runs-on: ubuntu-latest
+#     needs: [build]
+#     if: failure()  # Solo se ejecuta si run-tests falla
+#     steps:
+#       - name: Notificar Error
+#         uses: dawidd6/action-send-mail@v3
+#         with:
+#           server_address: smtp.gmail.com
+#           server_port: 465
+#           username: ${{ secrets.GMAIL_ADDRESS }}
+#           password: ${{ secrets.GMAIL_APP_PASSWORD }}
+#           subject: El repositorio ha fallado en las pruebas.
+#           body: El repositorio ha fallado en las pruebas. Puedes ver los detalles en https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}+event%3A${{ github.event_name }}
+#           to: ${{ secrets.GMAIL_ADDRESS_RECIPIENT }}
+#           from: ${{ secrets.GMAIL_ADDRESS }}
 
   build:
       runs-on: ubuntu-latest
-      needs:  [run-tests]
       steps:
         # 1. Checkout del código
         - name: Checkout code
@@ -173,7 +172,3 @@ jobs:
             WEB_SERVICE_URL: "https://labarbada.store/subirImagen.php"
             API_URL: "https://softion-api-v3.vercel.app/api/"  # Cambia por la URL de tu API
             PROJECT_NAME: "SoftionPro"  # Cambia este valor por el nombre de tu proyecto
-
-
-
-            
